scriptName CallGlobalFuncts Hidden

Function CallGlobalFunction(string ClassFunctName,string ArgListString) global native
Function CallInstanceFunction(string ClassFunctName,string ArgListString) global native